# Generated by Django 6.0.4 on 2026-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='specialist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
